import "./assets/styles/login.css";
import "./assets/styles/app.css";
import "./assets/styles/sidebar.css";
import "boxicons/css/boxicons.min.css";
import "./assets/styles/table.css";
import "./assets/styles/search.css";
import "./assets/styles/seat.css";
import "./assets/styles/card.css";
//import 'boxicons/css/boxicons.min.css';
